---
- name: Install the Netdata Linux agent on Debian
  include_tasks: install-debian.yml
  when: ansible_facts.os_family == "Debian"

- name: Install the Netdata Linux agent on OpenSUSE
  include_tasks: install-opensuse.yml
  when: ansible_facts.os_family == "Suse"

- name: Configure the Netdata Linux agent
  include_tasks: configure-linux.yml
  when: netdata_manage_config and ansible_facts.os_family != "Windows" and ansible_facts.os_family != "Darwin"

- name: Claim node if claim_token
  include_tasks: node_claim.yml
  when: netdata_claim_token | length > 0